from . import barakali_setla
from . import burger_va_hot_dog
from . import donarlar
from . import ichimliklar
from . import katta_pizza
from . import sneklar
from . import salatlar
from . import sandvich
from . import shirinlik
from . import sneklar
from . import yaxna_kofe
from . import souslar
from . import news
from . import lavash
