from . import barakalli_setlar_buttons
from . import burger_va_hot_doglar
from . import category_buttons
from . import donars_buttons
from . import hot_buttons
from . import ice_buttons
from . import ichimliklar_buttons
from . import inline_buttons
from . import lavashlar
from . import news_buttons
from . import pitsa
from . import salatlar_buttons
from . import savat_buttons
from . import sendvich
from . import shirinliklar
from . import souslar_buttons
from . import yozgi_ichimliklar
from . import yahna_kofe
from . import yozgi_ichimliklar
